language: csharp
solution: ConsoleApplication1.sln
install:
  - sudo apt-get install nunit-console
  - nuget restore ConsoleApplication1.sln
script:
  - xbuild ./ConsoleApplication1.sln
  - nunit-console ./UnitTestProject1/bin/Debug/UnitTestProject1.dll